services:
    consul:
        ports:
             - "8500:8500"

    userservice1.openapi:
        environment:
          - ASPNETCORE_ENVIRONMENT=Development
          - ServiceDiscovery__Id=userservice.openapi-9100
          - ServiceDiscovery__Name=userservice
          - ServiceDiscovery__ConsulUri=http://consul:8500
          - ServiceDiscovery__Address=userservice1.openapi
          - ServiceDiscovery__Port=8080
          - ServiceDiscovery__HealthCheckEndPoint__Uri="http://userservice1.openapi:8080/health"
        ports:
            - 9100:8080
        depends_on:
            - consul

    userservice2.openapi:
        environment:
          - ASPNETCORE_ENVIRONMENT=Development
          - ServiceDiscovery__Id=userservice.openapi-9200
          - ServiceDiscovery__Name=userservice
          - ServiceDiscovery__ConsulUri=http://consul:8500
          - ServiceDiscovery__Address=userservice2.openapi
          - ServiceDiscovery__Port=8080
          - ServiceDiscovery__HealthCheckEndPoint__Uri=http://userservice1.openapi:8080/health
        ports:
            - 9200:8080
        depends_on:
            - consul

    userservice3.openapi:
        environment:
          - ASPNETCORE_ENVIRONMENT=Development
          - ServiceDiscovery__Id=userservice.openapi-9300
          - ServiceDiscovery__Name=userservice
          - ServiceDiscovery__ConsulUri=http://consul:8500
          - ServiceDiscovery__Address=userservice3.openapi
          - ServiceDiscovery__Port=8080
          - ServiceDiscovery__HealthCheckEndPoint__Uri=http://userservice1.openapi:8080/health
        ports:
            - 9300:8080
        depends_on:
            - consul

    services.gateway:
        environment:
            - ServiceDiscovery__Address=services.gateway
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=http://+:8080
        ports:
            - 9500:8080
        depends_on:
            - consul
            - userservice1.openapi
            - userservice2.openapi
            - userservice3.openapi
